### ISSUE TITLE
[Feature Request / Question] delete last clipboard ( e.g. password)

### ISSUE THREAD

**Issue by LoneExile** [erebe/greenclip#132] opened 2022-08-19 16:00 UTC
I write a script to remove my recent clipboard but it seems broken the greenclip.history file.
Is there any work around?

```bash
#!/usr/bin/env bash

# grep only first line
RECENTLY=$(greenclip print | grep -m1 .)

echo "$RECENTLY"

# remove what i grep
sed -e s/"$RECENTLY"//g -i "$HOME/.cache/greenclip.history"
```

**Comment by heldergg** [comment] 2022-09-18 22:27
It would be nice to be able to remove any entry, something like:

`greenclip clear 15`

This would remove the 15th entry in the history file. This way we could manage the history file.

**Comment by erebe** [comment] 2023-01-28 08:26
closing as duplicate of #130

**Closed by erebe** 2023-01-28 08:26 UTC
Labels: enhancement
